name: FTP Deployment for Breederplants Project

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy-breederplants:
    environment: "plesk-breederplants"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Setup PHP 8.2 Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer Dependencies
        run: composer install

      - name: Setup Node.js 20 Environment
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # 🚀 Build the Portal Frontend for portal.breederplants.nl
      - name: Build Portal Frontend for Breederplants
        run: |
          cd frontend
          npm install
          npm run build -- --mode production
          cd ..

      # 🚀 Build the Public App Frontend for app.breederplants.nl
      - name: Build Public App Frontend for Breederplants App
        run: |
          cd frontend-app
          npm install
          npm run build -- --mode production
          cd ..

      # 🚀 Deploy the built Portal Frontend to portal.breederplants.nl via FTP
      - name: FTP Deploy Portal Frontend to portal.breederplants.nl
        uses: SamKirkland/FTP-Deploy-Action@v4.3.1
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ./
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            fileToExclude.txt
